# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  #    param_fetcher_listener:  true
  #    allowed_methods_listener:  true
  #    routing_loader: true
  view:
    view_response_listener:  true
  exception:
    enabled: true
    codes:
      App\Exceptions\NotFound\TrackObjectTypeNotFoundException: 404
      App\Exceptions\NotFound\RouteNotFoundException: 404
    messages:
      LogicException: false
  format_listener:
    rules:
      priorities: [json]
      fallback_format: json
      prefer_extension: true
